feat(Contact): Add contact us page
Trent-Computer-Science-Club-Association/ClubWebsite pull request #44
Opened 2024-09-08 00:53 UTC by spotandjake

This work was mostly done by Kara in #28 but we decided to rebranch do to the merge conflicts.

2024-09-09 05:23 UTC, amberwelby approved these changes
Looks really great guys! There's a lot here so I did my best but nothing major stood out. Just some silly lil questions but nothing that should stop a merge

2024-09-09 05:23 UTC, amberwelby commented on components/ContactForm.tsx
> +const emailRegex =
I'm just going to trust you on this one

2024-09-09 05:23 UTC, amberwelby commented on components/ContactForm.tsx
> +      case InputType.Group: {
Maybe I'm tired but why is there only one case? Is it in case we add more in the future?

2024-09-09 05:23 UTC, amberwelby commented on components/ContactForm.tsx
> +    case InputType.TextInput:
We don't need to do anything for this case?

2024-09-09 05:23 UTC, amberwelby commented on components/ContactForm.tsx
> +  formContent: FormItem[]; // This is going to be a reference
Was this a note you need to revisit?

2024-09-09 05:23 UTC, amberwelby commented on components/ContactForm.tsx
> +      clearForm();
We do have a successful submission messages displayed for the user right? I didn't test it, but assumed this is where I'd find it

2024-09-09 05:23 UTC, amberwelby commented on config.yaml
> +          priority: 1 # The lower the number, the higher the priority (with 1 being highest)
How is priority established? Is it decided by the listing closing date, given by whoever put the post up, etc. 
Also, how are items of the same priority sorted? Alphabetically, chronologically, order within this page?

2024-09-09 05:23 UTC, amberwelby commented on layouts/ContactSection.tsx
> +            submissionResponse.message = data.message;
I think this answers my question from earlier

2024-09-09 05:23 UTC, amberwelby commented on layouts/ListingsSection.tsx
> +        {sortedListings.slice(0, cardCount).map((listing, index) => (
What's the benefit of using the state instead of the constant here? Do we not want it to always (for what we have declared) be 0-3

2024-09-09 05:23 UTC, amberwelby commented on styles/components/BlurBanner.module.scss
> +      @apply bg-black/40;
does the / do something for opacity?

2024-09-10 14:38 UTC, Kara-Zor-El commented on config.yaml
> +          priority: 1 # The lower the number, the higher the priority (with 1 being highest)
its sorted by priority. so if its more important, the higher up it is on the page. priority isn't really up to us but by how badly they need it (ex. if hackathon is in a week and they still need more volunteers)

2024-09-10 14:39 UTC, Kara-Zor-El commented on styles/components/BlurBanner.module.scss
> +      @apply bg-black/40;
yes, opacity is at 0.4

2024-09-10 15:04 UTC, Kara-Zor-El commented on components/ContactForm.tsx
> +      case InputType.Group: {
ok so `default` checks if its a textInput or a dropDownInput. I agree that it should be inlined along the lines of this:
```ts
      case InputType.TextInput: {
        let valid = true;
        if (item.mandatory) {
          valid = item.value !== '';
          if (valid && isEmailItem(item)) {
            valid = emailRegex.test(item.value);
          }
        }
        isValid = isValid && valid;
        item.isValid = valid;
        return item;
      }
      case InputType.DropDownInput: {
        let valid = true;
        if (item.mandatory) {
          valid =
            item.value !== '' &&
            item.options.some(({ value }) => value === item.value);
        }
        isValid = isValid && valid;
        item.isValid = valid;
        return item;
      }
```

2024-09-10 18:52 UTC, Kara-Zor-El commented on components/ContactForm.tsx
> +const emailRegex =
```suggestion
// https://stackoverflow.com/a/46181
const emailRegex =
```

2024-09-10 23:14 UTC, Kara-Zor-El requested changes
Great job, fix changes then good to merge

2024-09-10 23:14 UTC, Kara-Zor-El commented on layouts/ListingsSection.tsx
> +          <Button
Hey I quite liked the button before and quite dislike the style of this button in this context. I think we should make a new button type or just use the one before here

2024-09-10 23:14 UTC, Kara-Zor-El commented on layouts/ListingsSection.tsx
> +      <Modal
when I designed this modal, it was not properly designed from a design standpoint. Are we happy with this UI or do you want a properly designed modal

2024-09-10 23:14 UTC, Kara-Zor-El commented on layouts/TextSection.tsx
> +      return ButtonStyle.Sponsor;
I think sponsor is a much too generic name for this. lets maybe think of a better name, ex. "Special"

2024-09-10 23:14 UTC, Kara-Zor-El commented on pages/api/submitForm.ts
> +  Name: z.string().max(200),
Whilst technically a name could be as big as possible, I think we should simplify it to maybe 100 characters. I think that leaves room for stuff such as: `name lastname, generic business co ltd incorporated, subsidiary of other business co ltd` which i think would be the upper echelon of names

2024-09-10 23:14 UTC, Kara-Zor-El commented on pages/api/submitForm.ts
> +  Email: z.string().max(200),
if were allowing emails this long, we should just set it to 256 as per https://www.rfc-editor.org/errata/eid1003

2024-09-10 23:14 UTC, Kara-Zor-El commented on pages/api/submitForm.ts
> +  res.setHeader('Access-Control-Allow-Methods', 'GET, POST');
why a get method if there if its a post only route

2024-09-10 23:14 UTC, Kara-Zor-El commented on styles/components/Footer.module.scss
>  }
the logo and buttons should probably be the one to stay and the email should be the one to go

2026-02-11 17:38 UTC, closed without merging